apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-service
        image: nicholasjackson/fake-service:v0.26.2
        ports:
        - name: http
          containerPort: 9091
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:9091"
        - name: "NAME"
          value: "backend"
        - name: "MESSAGE"
          value: "Hello from Backend Service!"
        - name: "HTTP_CLIENT_KEEP_ALIVES"
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  selector:
    app: backend
  ports:
  - port: 9090
    targetPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-service
        image: nicholasjackson/fake-service:v0.26.2
        ports:
        - name: http
          containerPort: 9090
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:9090"
        - name: "NAME"
          value: "frontend"
        - name: "MESSAGE"
          value: "Hello from Frontend Service!"
        - name: "UPSTREAM_URIS"
          value: "http://backend:9090"
        - name: "HTTP_CLIENT_KEEP_ALIVES"
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  selector:
    app: frontend
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090
  type: NodePort
